### ISSUE TITLE
[Documenting] H2 db integration checklist

### ISSUE THREAD

**Issue by plopezgit** [plopezgit/Sprint4_T2_SpringBoot_API_REST_H2#1]
Initial ref for H2 case: https://www.youtube.com/watch?v=hzEpwm_Ew7I&t=2110s

Checklist:

- [x] build the project zip
- [x] import the project on IDE
- [x] application properties setup

- [x] **creates model** 
- [x] >> annotate your entity classes with @ Entity to indicate they are JPA entities.
- [x] >> use @ Table to specify the table name if it's different from the class name.
- [x] >> use @ Id to specify the attribute that correlate with table primary key.
- [x] >>> use @ GeneratedValue to set auto increment up.
- [x] >>>> set GeneratedValue' 'strategy' as GenerationType.IDENTITY

- [x] **creates repository interface**
- [x] >> repository interface extends of interface JPARepository (https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html). This interface heritage declaration must indicates
- [x] >>> The object type or resource that will be repo
- [x] >>> and the object type that would identify that resource
- [x] use the @ Repository stereotype annotation to set the repository interface as repo and be sure the bean would be scanned and contained.

- [x] **creates service class**
- [x] >> inject repository object by using @ Autowired bean factory
- [x] >> develop CRUD methods by using JPARepository object inherited method-
 
- [x]  **creates controller class**
- [x] >> uses @ RestController bind annotation to set the class as controller and expose the CRUD endpoints
- [x] >> user @ RequestMapping bind annotation to set the access path for the endpoints
- [x] >> inject service object by using @ Autowired bean factory
- [x] >> develop CRUD endpoint method (using @ GetMapping, PostMapping, DeleteMapping,  PutMapping diverse propose annotations to map the path; and  using @ PathVariable, @ RequestBody to inject endpoint method parameters)
- [x] >>> CRUD method should return ResponseEntity<T>  (crud endpoint method return example:  new ResponseEntity<>(newFruit, HttpStatus.CREATED);)
- [x] >>>> refactor and enhance method by following example:

```
***@PostMapping Example***
@PostMapping(path = "users", 
        consumes = MediaType.APPLICATION_JSON_VALUE, 
        produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<User> create(@RequestBody User newUser) {

    User user = userService.save(newUser);
    if (user == null) {
        throw new ServerException();
    } else {
        return new ResponseEntity<>(user, HttpStatus.CREATED);
    }
}
```
- [x] H2 database view access
- [x] Postman collection 
- [x] Tests
- [x] Database check

![Image](https://github.com/plopezgit/Sprint4_T2_SpringBoot_H2/assets/131781567/4c95b499-cc9e-4338-b494-eee143170fca)
![Image](https://github.com/plopezgit/Sprint4_T2_SpringBoot_H2/assets/131781567/a5dcf083-5575-4a3c-9ccc-aad89b6a7360)
